service: strava-kom-api

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    CLIENT_ID: ${file(./env.json):CLIENT_ID}
    CLIENT_SECRET: ${file(./env.json):CLIENT_SECRET}
plugins:
  - serverless-offline
functions:
  login:
    handler: lib/index.login
    events:
      - http:
          path: login
          method: get
          cors: true

